Traceback (most recent call last):
  File "/Users/catherinez/VSC/ml-modeling-deorphanize/model_training/train.py", line 264, in <module>
    main()
  File "/Users/catherinez/VSC/ml-modeling-deorphanize/model_training/train.py", line 261, in main
    run_training(model_config_path, data_config_path)
  File "/Users/catherinez/VSC/ml-modeling-deorphanize/model_training/train.py", line 238, in run_training
    trainer.train(train_loader, valid_loader)
  File "/Users/catherinez/VSC/ml-modeling-deorphanize/model_training/train.py", line 88, in train
    batch_inputs = {k: v.to(self.device) for k, v in features.items()}
  File "/Users/catherinez/VSC/ml-modeling-deorphanize/model_training/train.py", line 88, in <dictcomp>
    batch_inputs = {k: v.to(self.device) for k, v in features.items()}
AttributeError: 'list' object has no attribute 'to'
